package com.example.Controllers;

import Classes.Article;
import Classes.DatabaseHandler;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.TextArea;
import javafx.scene.control.TextField;
import javafx.stage.FileChooser;
import javafx.stage.Stage;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Date;

public class AddArticleController {

    @FXML
    private TextField titTXT; // Article title input
    @FXML
    private TextField titTXT2; // Source input
    @FXML
    private TextArea artTXT; // Content display area
    @FXML
    private TextField titTXT1; // Category display

    @FXML
    private Button chooseFileButton; // Button to choose the file

    private final DatabaseHandler dbHandler = new DatabaseHandler();
    private File selectedFile;

    @FXML
    private void initialize() {
        // Setting the action for the "Choose File" button
        chooseFileButton.setOnAction(event -> chooseFile());
    }

    @FXML
    // This method is used to choose a text file for the article content
    private void chooseFile() {
        FileChooser fileChooser = new FileChooser();
        fileChooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("Text Files", "*.txt"));
        selectedFile = fileChooser.showOpenDialog(new Stage());

        if (selectedFile != null) {
            try (BufferedReader reader = new BufferedReader(new FileReader(selectedFile))) {
                StringBuilder content = new StringBuilder();
                String line;
                while ((line = reader.readLine()) != null) {
                    content.append(line).append("\n");
                }
                artTXT.setText(String.valueOf(content));
            } catch (IOException ex) {
                ex.printStackTrace();
                artTXT.setText("Error reading the file.");
            }
        }
    }

    @FXML
    private void uploadArticle() {
        // Retrieve input values
        String title = titTXT.getText();
        String source = titTXT2.getText();
        String content = artTXT.getText();

        // Validate inputs
        if (title.isEmpty() || source.isEmpty() || content.isEmpty()) {
            artTXT.setText("Please fill in all required fields and choose a file.");
            return;
        }

        // Identify the category using NLP
        String category = identifyCategory(content);


        // Create an Article object
        Article article = new Article(
                0, // articleID is auto-generated by the database
                title,
                content,
                category,
                source,
                new Date() // Current date
        );

        // Add the article to the database
        try {
            dbHandler.addArticle(article);
            artTXT.setText("Article uploaded successfully!");
        } catch (Exception e) {
            e.printStackTrace();
            artTXT.setText("Error uploading article.");
        }
        titTXT1.setText(category); // Display the identified category
    }

    /**
     * Identifies the category of the article content using NLP.
     *
     * @param content The article content to analyze.
     * @return The identified category.
     */
    private String identifyCategory(String content) {
        // Example of simple keyword-based NLP categorization
        if (content.toLowerCase().contains("technology")) {
            return "Technology";
        } else if (content.toLowerCase().contains("health")) {
            return "Health";
        } else if (content.toLowerCase().contains("sports")) {
            return "Sports";
        } else {
            return "General";
        }
    }

    /**
     * Clears the fields to allow the admin to add a new article.
     */
    private void clearFields() {
        titTXT.clear();
        titTXT2.clear();
        artTXT.clear();
        titTXT1.clear();
        selectedFile = null;
    }

    @FXML
    protected void toAdminOptions(ActionEvent e) throws IOException {
        Stage stage = new Stage();
        Parent root = FXMLLoader.load(getClass().getResource("adminOptions.fxml"));
        stage.setScene(new Scene(root,600, 400));
        stage.show();


        Stage previousStage = (Stage) ((Node)e.getSource()).getScene().getWindow();
        previousStage.close();
    }
}
